### ISSUE TITLE
Improve README on how to manage DNS

### ISSUE THREAD

**Issue by fedecastelli** [CreateInCloud/webflow-aws#8]
Before the section `Create webflow-aws-config.yaml file`, add a section to explain how to manage domains:

- Using Route53: the user has to create a hosted zone and all the required records will be created automatically. Place here a link of **Medium article**.
- Using a different DNS: the user needs to know which records have to create inside his DNS. 

Also, explain how to manage all the domains (the CNAMEs).

**Comment by 70nyIT** [comment]
Merged in develop. Check if it's good and eventually merge to master.
